name: Test with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
       
    - name: Test with Gradle
      run: ./gradlew test
